// For Next.js App Router, add to your layout.tsx
import type { Metadata } from 'next';
import './globals.css';
import { RoomQueryProvider } from '@/components/Providers/query-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning id='root' className="mdl-js">
        <RoomQueryProvider>
          {children}
        </RoomQueryProvider>
      </body>
    </html>
  );
}